apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  labels:
    app: navidrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
    spec:
      containers:
      - name: navidrome
        image: deluan/navidrome:latest
        env:
        - name: ND_CONFIGFILE
          value: "/config/navidrome.toml"
        ports:
        - containerPort: 4533
        volumeMounts:
        - name: music-volume
          mountPath: /music
        - name: data-volume
          mountPath: /data
        - name: config-volume
          mountPath: /config
          readOnly: true
      volumes:
      - name: music-volume
        hostPath:
          path: PLACEHOLDER_MUSIC
          type: Directory
      - name: data-volume
        hostPath:
          path: PLACEHOLDER_DATA
          type: Directory
      - name: config-volume
        configMap:
          name: server-config
---
apiVersion: v1
kind: Service
metadata:
  name: music-service
spec:
  selector:
    app: navidrome
  ports:
  - protocol: TCP
    port: 8027
    targetPort: 4533
