apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
spec:
  template:
    spec:
      volumes:
        - name: music-volume
          hostPath:
            path: /mnt/music
        - name: data-volume
          hostPath:
            path: /mnt/navidrome-data

