apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
spec:
  template:
    spec:
      volumes:
      - name: music-volume
        hostPath:
          path: /srv/volumes/music
      - name: data-volume
        hostPath:
          path: /srv/volumes/navidrome-data
