apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-tgbot
spec:
  template:
    spec:
      containers:
        - name: bot
          image: registry.local/music-tgbot:dev
      volumes:
        - name: music-volume
          hostPath:
            path: /mnt/music
